<?php

/**
 * The doublclick URL.
 */
define('DART_URL', 'http://ad.doubleclick.net');

/**
 * The maximum number of key|value pair fields to show on forms by defaut.
 */
define('DART_MAX_KEY_VALS', 10);

/**
 * Implementation of hook_help().
 */
function dart_help($path, $arg) {
  switch ($path) {
    case 'admin/help#dart':
      $output = '<p>'. t('The DART module allows you to integrate Doubleclick ad tags onto your site.') . '</p>';
      $output .= '<p>'. t('This module provides you with a general settings form as well as the ability to create a tag (with all its associated data) in the database. You can then add a simple bit of php to your tpl.php file(s) within your theme to indicate where specific tags should be displayed.') . '</p>';
      $output .= '<p>'. t('In addition, you can tell this module about specific javascript variables that exist on your pages in order to include them in your ad tags. For example, you can include a variable called "channel" with a value of "sports".') . '</p>';
      return $output;
  }
}

/**
 * Implementation of hook_perm().
 */
function dart_perm() {
  return array('administer DART tags');
}

/**
 * Implementation of hook_theme().
 */
function dart_theme() {
  return array(
    'dart_key_vals_form' => array(
      'arguments' => array('form'),
      'file'      => 'plugins/export_ui/dart_ctools_export_ui.inc',
    ),
    'dart_global_defaults_form' => array(
      'arguments' => array('form'),
      'file'      => 'dart.admin.inc',
    ),
    'dart_tag' => array(
      'arguments' => array('tag' => NULL),
      'template'  => 'theme/dart_tag',
    ),
  );
}

/**
 * Implementation of hook_menu().
 */
function dart_menu() {
  $items = array();

  $items['admin/build/dart_tags/settings'] = array(
    'title'             => 'Global DART Settings',
    'type'              => MENU_LOCAL_TASK,
    'description'       => "Configure your site-wide DART settings.",
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('dart_admin_settings'),
    'access arguments'  => array('administer DART tags'),
    'file'              => 'dart.admin.inc',
    'weight'            => 50,
  );
  $items['admin/build/dart_tags/test_page'] = array(
    'title'             => 'DART Test Page',
    'type'              => MENU_LOCAL_TASK,
    'description'       => "View all your DART tags",
    'page callback'     => 'dart_test_page',
    'access arguments'  => array('administer DART tags'),
    'weight'            => 55,
  );

  return $items;
}

/**
 * Implementation of hook_block().
 */
function dart_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $tags = _dart_block_tags();
      foreach ($tags as $tag) {
        $block['dart-tag-'. $tag->machinename]['info'] = t('DART tag: !tagname', array('!tagname' => $tag->name));
      }
      break;
    case 'configure':
      break;
    case 'save':
      break;
    case 'view':
      $machinename = str_replace('dart-tag-', '', $delta);
      $block['content'] = dart_tag($machinename);
      break;
  }
  if (isset($block)) {
    return $block;
  }
}

/**
 * Implementation of hook_ctools_plugin_directory().
 */
function dart_ctools_plugin_directory($module, $type) {
  // Load the export_ui plugin.
  if ($type == 'export_ui') {
    return 'plugins/export_ui';
  }
}

/**
 * Implementation of hook_context_plugins().
 */
function dart_context_plugins() {
  $plugins = array();
  $plugins['dart_context_reaction_tags'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'dart') .'/plugins/contexts',
      'file' => 'dart_context_reaction_tags.inc',
      'class' => 'dart_context_reaction_tags',
      'parent' => 'context_reaction',
    ),
  );
  return $plugins;
}

/**
 * Implementation of hook_context_registry().
 */
function dart_context_registry() {
  return array(
    'reactions' => array(
      'dart_tags' => array(
        'title' => t('DART tags'),
        'plugin' => 'dart_context_reaction_tags',
      ),
    ),
  );
}

/**
 * Wrapper function for outputting a themed dart tag.
 */
function dart_tag($machinename) {
  $output = '';
  $show_tag = TRUE;

  // Check if the tag should be hidden based on the current context.
  if (function_exists('context_get_plugin')) {
    $plugin = context_get_plugin('reaction', 'dart_tags');
    $show_tag = $plugin->execute($machinename);
  }

  // Make sure this is a real tag.
  if (!$tag = dart_tag_load($machinename)) {
    drupal_set_message(t('%machinename is not a valid DART tag.', array('%machinename' => $machinename)), 'error');
    return;
  }

  if ($tag->active && $show_tag) {
    // Build the tag based on its display options.
    // $output = dart_tag_build($tag);
    $output = theme('dart_tag', $tag);
  }

  return $output;
}

/**
 * Return the adtag object matching a DART Tag ID.
 *
 * @param $machinename
 *   The DART tag's unique identifier or empty.
 *
 * @return
 *   If a machinename is provided, the dart tag object with all of its metadata,
 *   if it exists, NULL otherwise. If machinename is empty, a list of all dart
 *   tags.
 */
function dart_tag_load($machinename = '') {
  ctools_include('export');

  // Grab an array of all DART tags or the specificed DART tag. 
  if (empty($machinename)) {
    $tags = ctools_export_load_object('dart_tags');
  }
  else {
    $tags = ctools_export_load_object('dart_tags', 'names', array($machinename));
  }

  // Build up the tag objects
  dart_tag_prepare($tags);
  return empty($machinename) ? $tags : array_shift($tags);
}

/**
 * Modify just-loaded DART tags to prepare it for use.
 */
function dart_tag_prepare(&$tags) {
  // Unserialize the settings array.
  foreach ($tags as &$tag) {
    if (is_string($tag->settings)) {
      $tag->settings = unserialize($tag->settings);
    }

    // Build an exhaustive key_vals array to use for display purposes that
    // incorporates global, special & tag-specific key|value pairs.
    $tag->key_vals = array();
    $pos_sz_key_vals = array(array('key' => 'pos', 'val' => $tag->pos, 'eval' => FALSE), array('key' => 'sz', 'val' => $tag->sz, 'eval' => FALSE));
    $global_key_vals = variable_get('dart_key_vals', array());
    $tag_key_vals = isset($tag->settings['key_vals']) ? $tag->settings['key_vals'] : array();
    $contrib_key_vals = module_invoke_all('dart_key_vals', $tag);
    $special_key_vals  = _dart_get_special_key_vals();

    // Merge these key_value arrays together. $special_key_vals must be last.
    $key_vals = array_merge(
      $pos_sz_key_vals,
      $global_key_vals,
      $tag_key_vals,
      $contrib_key_vals,
      $special_key_vals
    );

    // Use an MD5 hash trick to ensure no duplicate key|value pairs exist.
    $unique_key_vals = array();
    foreach ($key_vals as $pair) {
      $unique_key_vals[md5(serialize($pair))] = $pair;
    }
    $key_vals = array_values($unique_key_vals);

    foreach ($key_vals as $pair) {
      _dart_add_key_val($tag, $pair['key'], $pair['val'], $pair['eval']);
    }

    // Set the prefix.site/zone and slug for this tag.
    $variables = array('prefix', 'site', 'zone', 'slug');
    foreach ($variables as $var){
      $tag->{$var} = empty($tag->settings['overrides'][$var]) ? variable_get('dart_global_' . $var, '') : $tag->settings['overrides'][$var];
    }
    $tag->slug = ($tag->slug != '<none>' ? $tag->slug : '');

    // Give other modules the opportunity to add information to this tag.
    drupal_alter('dart_tag', $tag);

    // Build data for the noscript tag.
    $tag->noscript = dart_tag_prepare_noscript($tag);

    // Check if tags should be displayed using test values for prefix.site/zone().
    dart_tag_adtest($tag);
  }
}

/**
 * Build data for the noscript tag.
 */
function dart_tag_prepare_noscript($tag) {
  static $tile = NULL;
  static $ord = 0;

  // Set an initial value for tile.
  $tile = is_null($tile) ? variable_get('dart_special_tile_init', '0') : $tile;

  // Add the special key|value pairs to the noscript tag.
  $special_key_vals = _dart_get_special_key_vals();
  if (isset($special_key_vals['tile'])) {
    $tile++;
  }
  if (isset($special_key_vals['ord'])) {
    $ord = $ord == 0 ? rand(1000000000, 9999999999) . '?' : $ord;
  }

  // Begin building the src for the noscript tag.
  $src  = DART_URL . '/ad/' . $tag->prefix . '.' . $tag->site . '/' . $tag->zone . ';pos=' . $tag->pos . ';sz=' . $tag->sz . ';';

  // Add global & tag-specific key|value pairs.
  foreach ($tag->key_vals as $key=>$vals) {
    foreach ($vals as $val) {
      // Only add key|value pairs that do not require javacript and are not
      // "special" key|value pairs.
      if (!$val['eval'] && !in_array($key, $special_key_vals)) {
        $src .= $key . '=' . $val['val'] . ';';
      }
    }
  }

  // Now add the "special" key|value pairs.
  $src .= $tile ? 'tile=' . $tile .';' : '';
  $src .= $ord ? 'ord=' . $ord : '';

  return array(
    'src'   => $src,
    'href'  => str_ireplace('/ad/', '/jump/', $src),
  );
}

/**
 * Change the current active/inactive status for the given tag.
 */
function dart_tag_set_status($tag, $status) {
  db_query("UPDATE {dart_tags} SET active = %d WHERE machinename = '%s'", $status, $tag->machinename);
}

/**
 * Implentation of template_preprocess_page().
 */
function dart_preprocess_page(&$variables) {
  // Inject any user-defined javascript.
  $inline_js = variable_get('dart_js', '') . "\n";
  
  // Add page key|value pairs to the drupal.settings.dart javascript variable.
  $key_vals = _dart_get_page_key_vals();

  foreach ($key_vals as $key => $val) {
    $inline_js .= 'var ' . $key . ' = ' . $val . ';' . "\n";
  }

  // Include the inline js & dart.js file.
  drupal_add_js(trim($inline_js, "\n"), 'inline');
  drupal_add_js(drupal_get_path('module', 'dart') . '/dart.js');

  // Regenerate scripts variable to incorporate newly added scripts.
  $variables['scripts'] = drupal_get_js();
}

/**
 * Menu callback; Displays all DART tags on a single page for testing purposes.
 */
function dart_test_page() {
  $tags = dart_tag_load();

  $output  = drupal_get_form('dart_test_page_form');
  foreach ($tags as $tag) {
    $tag->mode = 'test';
    $tag->site = isset($_GET['site']) ? $_GET['site'] : $tag->site;
    $tag->zone = isset($_GET['zone']) ? $_GET['zone'] : $tag->zone;

    $tag_markup = theme('dart_tag', $tag);

    $output .= '<div class="ad_wrap">';
    $output .= '<h2>' . $tag->name . '</h2>';
    $output .= $tag_markup;
    if (module_exists('devel')) {
      $output .= kpr($tag, TRUE);
    }
    $output .= '</div>';
  }
  return $output;
}

/**
 * Form function for the override settings at the top of the test page.
 */
function dart_test_page_form(&$form_state, $edit=array()) {
  $form['#method'] = 'get';
  $form['site'] = array(
    '#type'           => 'textfield',
    '#title'          => t('Site'),
    '#default_value'  => $_GET['site'],
  );
  $form['zone'] = array(
    '#type'           => 'textfield',
    '#title'          => t('Zone'),
    '#default_value'  => $_GET['zone'],
  );
  $form['submit'] = array(
    '#type'           => 'submit',
    '#value'          => t('Override'),
  );

  return $form;
}

/**
 * Alters tags to use test prefix.site.zone if the adtest query string.
 */
function dart_tag_adtest(&$tag) {
  // If there is an "adtest" query string, show test ad tags instead.
  if (isset($_GET['adtest']) && $_GET['adtest'] == 'true') {
    $tag->prefix = $_GET['prefix'] ? $_GET['prefix'] : variable_get('dart_test_prefix', '');
    $tag->site = $_GET['site'] ? $_GET['site'] : variable_get('dart_test_site', '');
    $tag->zone = $_GET['zone'] ? $_GET['zone'] : variable_get('dart_test_zone', '');
  }
}

/**
 * Helper function defines the structure of the tag settings array.
 */
function _dart_tag_settings_data_structure() {
  $structure = array(
    'overrides' => array('site', 'zone', 'slug'),
    'options'   => array('scriptless', 'method'),
    'key_vals'  => array(),
  );

  drupal_alter('dart_tag_settings_data_structure', $structure);

  return $structure;
}

/**
 * Helper function that returns an array of all tags that will
 * be rendered as blocks.
 */
function _dart_block_tags() {
  $block_tags = array();
  $tags = dart_tag_load();

  foreach ($tags as $tag) {
    if ($tag->block) {
      $block_tags[] = $tag;
    }
  }

  return $block_tags;
}

/**
 * Helper function to add a key|value pair to a tag object.
 */
function _dart_add_key_val(&$tag, $key, $val = NULL, $eval = FALSE) {
  if (!empty($val)) {
    $tag->key_vals[$key][] = array('val' => $val, 'eval' => $eval);
  }
}

/**
 * Helper function to buil a key|value pair array for special_key_vals.
 */
function _dart_get_special_key_vals() {
  $key_vals = array();

  $special_key_vals = variable_get('dart_special_key_vals', array());
  foreach ($special_key_vals as $key => $val) {
    if (!empty($val)) {
      switch($key) {
        case 'ord':
          $key_vals[] = array(
            'key' => $key,
            'val' => 'ord',
            'eval' => TRUE,
          );
          break;
        case 'tile':
          $key_vals[] = array(
            'key' => $key,
            'val' => 'tile++',
            'eval' => TRUE,
          );
          break;
      }
    }
  }
  return $key_vals;
}

/**
 * Returns an array of js variables to be included at the top of every page.
 */
function _dart_get_page_key_vals() {
  //$key_vals = array('dart' => array());
  $key_vals = array();

  // Set the dart url
  $key_vals['dart_url'] = '"' . DART_URL . '"';

  // Setup page-wide Dart key|value pairs as varibales.
  foreach (_dart_get_special_key_vals() as $key_val) {
    if (!empty($key_val['val'])) {
      switch ($key_val['key']) {
        case 'ord':
          $key_vals['ord'] = "1000000000 + Math.floor(Math.random() * 900000000)";
          break;
        case 'tile':
          $key_vals['tile'] = variable_get('dart_special_tile_init', '0');
          break;
      }
    }

  }
  return $key_vals;
}

/**
 * Template preprocess function for dart tags.
 */
function template_preprocess_dart_tag(&$variables) {
  $tag = $variables['tag'];

  $variables['attributes']  = array('class' => 'dart-tag');
  $variables['json_tag']    = drupal_to_js($tag);

  if (isset($tag->mode) && $tag->mode == 'test') {
    $variables['show_script_tag']   = TRUE;
    $variables['show_noscript_tag'] = TRUE;  
  }
  else {
    $variables['show_script_tag']   = !$tag->settings['options']['scriptless'];
    $variables['show_noscript_tag'] = variable_get('dart_noscript', 1);
  }
  $variables['noscript_tag']      = $variables['show_noscript_tag'] ? '<noscript>' . l(theme('image', $tag->noscript['src'], '', '', NULL, FALSE), $tag->noscript['href'], array('html' => TRUE)) . '</noscript>' : '';

  $variables['tag'] = $tag;
}
