<?php

/**
 * Implements hook_dart_key_vals().
 */
function dart_search_dart_key_vals($tag) {
  $key_vals = array();

  if (arg(0) == 'search') {
    $keys = dart_search_get_keys();

    foreach ($keys as $key) {
      $key_vals[] = array(
        'key' => 'term',
        'val' => drupal_strtolower(preg_replace("/[^A-Za-z0-9_\-]/", "", str_replace(' ', variable_get('dart_key_vals_separator', '-'), $key))),
        'eval' => FALSE,
      );
    }

  }

  return $key_vals;
}

/**
 * Helper function for grabbing search keys. Function is missing in D7.
 * Coppied from google_analytics
 *
 * http://api.drupal.org/api/function/search_get_keys/6
 */
function dart_search_get_keys() {
  static $return;

  if (!isset($return)) {
    $path = explode('/', $_GET['q'], 3);

    if (count($path) == 3) {
      $return = explode(' ', $path[2]);
    }
  }

  return $return;
}
